# Generated by Django 6.0.3 on 2026-03-18 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('fecha_evento', models.DateField()),
                ('local_afectado', models.CharField(choices=[('apoquindo', 'Apoquindo'), ('las_tranqueras', 'Las Tranqueras'), ('vitacura', 'Vitacura'), ('san_carlos_de_apoquindo', 'San Carlos de Apoquindo'), ('cristobal_colon', 'Cristobal Colon'), ('isabel_la_catolica', 'Isabel la Catolica'), ('luis_pasteur', 'Luis Pasteur'), ('la_dehesa', 'La Dehesa'), ('colina', 'Colina')], max_length=50)),
                ('tipo_evento', models.CharField(choices=[('lluvia', 'Lluvia'), ('frio', 'Frio'), ('evento_deportivo', 'Evento Deportivo'), ('elecciones', 'Elecciones'), ('corte_de_suministro', 'Corte de Suministro'), ('cuarentena', 'Cuarentena'), ('desastre_natural', 'Desastre Natural'), ('trabajo_o_reparaciones', 'Trabajo o Reparaciones'), ('falla_de_equipos', 'Falla de Equipos'), ('dia_festivo', 'Día Festivo'), ('temas_productivos', 'Temas Productivos'), ('otros', 'Otros')], max_length=50)),
                ('detalles_evento', models.TextField(blank=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
