# Generated by Django 6.0.3 on 2026-03-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='fecha_registro',
        ),
    ]
