# Generated by Django 6.0.3 on 2026-03-18 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_eventos_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
